### ISSUE TITLE
怎么使用

### ISSUE THREAD

**Issue by mrli20182018** [frostspb/aio_api_ros#1]
![image](https://user-images.githubusercontent.com/42336683/54363439-e8c0ac00-46a5-11e9-9a50-a82cb097b350.png)

 请问怎么使用？

**Comment by frostspb** [comment]
i think u must del lead space in 
`mk.talk_word('/ip/service/print')`
its looks like
`mk.talk_word(' /ip/service/print')`

can you try this code?
```python
res = await mk.read(256) # or 64 or something
print(res.decode())
```

**Comment by mrli20182018** [comment]
> 我认为你必须在
> `mk.talk_word('/ip/service/print')`
> 它的外观中引领空间
> `mk.talk_word(' /ip/service/print')`
> 
> 你能试试这段代码吗？
> 
> ```python
> res =  await mk.read（256）＃或64或
> print（res.decode（））
> ```

![image](https://user-images.githubusercontent.com/42336683/54401671-8d250b80-4703-11e9-964d-e6882f8a183e.png)

我是新手 

![image](https://user-images.githubusercontent.com/42336683/54401709-b6459c00-4703-11e9-9b33-5a904308cb1f.png)
能返回所有结果吗？

**Comment by frostspb** [comment]
This should help
```python
res = await mk.read(1024)
```
Its low level function.
I think , in the next version I will make a function to read the full response

**Comment by frostspb** [comment]
OK.
I have released a new version 0.0.8. Now the function "read" parses the answer with flag parse=True (default behavior)
```python
res = await mk.read() 
print(res)
```

if you need original response
```python
res = await mk.read(parse=False) 
print(res.decode())
```

**Comment by mrli20182018** [comment]
> 好。
> 我发布了0.0.8的新版本。现在函数“read”用flag parse = True解析答案（默认行为）
> 
> ```python
> res =  await mk.read（） 
>  print（res）
> ```
> 
> 如果你需要原始回复
> 
> ```python
> res =  await mk.read（parse = False） 
>  print（res.decode（））
> ```

![image](https://user-images.githubusercontent.com/42336683/54434041-45849b00-4768-11e9-9d23-34c012de1e63.png)
不是返回所有？

**Comment by frostspb** [comment]
Fixed in v 0.0.9

if you want  to see full personse:
```python
res =  await mk.read(full_answer=True）
```
result:

```
('!re', None, {'.id': '*8', 'name': 'winbox', 'port': 8291, 'address': '', 'invalid': False, 'disabled': False})

('!re', None, {'.id': '*9', 'name': 'api-ssl', 'port': 8729, 'address': '', 'certificate': 'none', 'invalid': False, 'disabled': False})

('!done', None, {})
```
without this params:

```python
res =  await mk.read(）
```

```
{'.id': '*8', 'name': 'winbox', 'port': 8291, 'address': '', 'invalid': False, 'disabled': False}
{'.id': '*9', 'name': 'api-ssl', 'port': 8729, 'address': '', 'certificate': 'none', 'invalid': False, 'disabled': False}
```

**Comment by mrli20182018** [comment]
![image](https://user-images.githubusercontent.com/42336683/54491203-819a3600-48f7-11e9-8eb2-a0e1e17a91b5.png)

这就是我要的  
谢谢
api语法我还不是很会

**Comment by frostspb** [comment]
Thank you for testing
